# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_ada_parse <- function(input_vec, decode) {
    .Call(`_adaR_Rcpp_ada_parse`, input_vec, decode)
}

Rcpp_ada_has_credentials <- function(url_vec) {
    .Call(`_adaR_Rcpp_ada_has_credentials`, url_vec)
}

Rcpp_ada_has_empty_hostname <- function(url_vec) {
    .Call(`_adaR_Rcpp_ada_has_empty_hostname`, url_vec)
}

Rcpp_ada_has_hostname <- function(url_vec) {
    .Call(`_adaR_Rcpp_ada_has_hostname`, url_vec)
}

Rcpp_ada_has_non_empty_username <- function(url_vec) {
    .Call(`_adaR_Rcpp_ada_has_non_empty_username`, url_vec)
}

Rcpp_ada_has_non_empty_password <- function(url_vec) {
    .Call(`_adaR_Rcpp_ada_has_non_empty_password`, url_vec)
}

Rcpp_ada_has_port <- function(url_vec) {
    .Call(`_adaR_Rcpp_ada_has_port`, url_vec)
}

Rcpp_ada_has_hash <- function(url_vec) {
    .Call(`_adaR_Rcpp_ada_has_hash`, url_vec)
}

Rcpp_ada_has_search <- function(url_vec) {
    .Call(`_adaR_Rcpp_ada_has_search`, url_vec)
}

Rcpp_ada_get_href <- function(url_vec, decode) {
    .Call(`_adaR_Rcpp_ada_get_href`, url_vec, decode)
}

Rcpp_ada_get_username <- function(url_vec, decode) {
    .Call(`_adaR_Rcpp_ada_get_username`, url_vec, decode)
}

Rcpp_ada_get_password <- function(url_vec, decode) {
    .Call(`_adaR_Rcpp_ada_get_password`, url_vec, decode)
}

Rcpp_ada_get_port <- function(url_vec, decode) {
    .Call(`_adaR_Rcpp_ada_get_port`, url_vec, decode)
}

Rcpp_ada_get_hash <- function(url_vec, decode) {
    .Call(`_adaR_Rcpp_ada_get_hash`, url_vec, decode)
}

Rcpp_ada_get_host <- function(url_vec, decode) {
    .Call(`_adaR_Rcpp_ada_get_host`, url_vec, decode)
}

Rcpp_ada_get_hostname <- function(url_vec, decode) {
    .Call(`_adaR_Rcpp_ada_get_hostname`, url_vec, decode)
}

Rcpp_ada_get_pathname <- function(url_vec, decode) {
    .Call(`_adaR_Rcpp_ada_get_pathname`, url_vec, decode)
}

Rcpp_ada_get_search <- function(url_vec, decode) {
    .Call(`_adaR_Rcpp_ada_get_search`, url_vec, decode)
}

Rcpp_ada_get_protocol <- function(url_vec, decode) {
    .Call(`_adaR_Rcpp_ada_get_protocol`, url_vec, decode)
}

Rcpp_ada_set_href <- function(url_vec, subst, decode) {
    .Call(`_adaR_Rcpp_ada_set_href`, url_vec, subst, decode)
}

Rcpp_ada_set_username <- function(url_vec, subst, decode) {
    .Call(`_adaR_Rcpp_ada_set_username`, url_vec, subst, decode)
}

Rcpp_ada_set_password <- function(url_vec, subst, decode) {
    .Call(`_adaR_Rcpp_ada_set_password`, url_vec, subst, decode)
}

Rcpp_ada_set_port <- function(url_vec, subst, decode) {
    .Call(`_adaR_Rcpp_ada_set_port`, url_vec, subst, decode)
}

Rcpp_ada_set_host <- function(url_vec, subst, decode) {
    .Call(`_adaR_Rcpp_ada_set_host`, url_vec, subst, decode)
}

Rcpp_ada_set_hostname <- function(url_vec, subst, decode) {
    .Call(`_adaR_Rcpp_ada_set_hostname`, url_vec, subst, decode)
}

Rcpp_ada_set_pathname <- function(url_vec, subst, decode) {
    .Call(`_adaR_Rcpp_ada_set_pathname`, url_vec, subst, decode)
}

Rcpp_ada_set_protocol <- function(url_vec, subst, decode) {
    .Call(`_adaR_Rcpp_ada_set_protocol`, url_vec, subst, decode)
}

Rcpp_ada_set_search <- function(url_vec, subst, decode) {
    .Call(`_adaR_Rcpp_ada_set_search`, url_vec, subst, decode)
}

Rcpp_ada_set_hash <- function(url_vec, subst, decode) {
    .Call(`_adaR_Rcpp_ada_set_hash`, url_vec, subst, decode)
}

Rcpp_ada_clear_port <- function(url_vec, decode) {
    .Call(`_adaR_Rcpp_ada_clear_port`, url_vec, decode)
}

Rcpp_ada_clear_hash <- function(url_vec, decode) {
    .Call(`_adaR_Rcpp_ada_clear_hash`, url_vec, decode)
}

Rcpp_ada_clear_search <- function(url_vec, decode) {
    .Call(`_adaR_Rcpp_ada_clear_search`, url_vec, decode)
}

Rcpp_url_decode2 <- function(url) {
    .Call(`_adaR_Rcpp_url_decode2`, url)
}

url_reverse <- function(urls) {
    .Call(`_adaR_url_reverse`, urls)
}

