# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_ada_parse <- function(input_vec) {
    .Call(`_adaR_Rcpp_ada_parse`, input_vec)
}

Rcpp_ada_has_credentials <- function(input) {
    .Call(`_adaR_Rcpp_ada_has_credentials`, input)
}

Rcpp_ada_has_empty_hostname <- function(input) {
    .Call(`_adaR_Rcpp_ada_has_empty_hostname`, input)
}

Rcpp_ada_has_hostname <- function(input) {
    .Call(`_adaR_Rcpp_ada_has_hostname`, input)
}

Rcpp_ada_has_non_empty_username <- function(input) {
    .Call(`_adaR_Rcpp_ada_has_non_empty_username`, input)
}

Rcpp_ada_has_non_empty_password <- function(input) {
    .Call(`_adaR_Rcpp_ada_has_non_empty_password`, input)
}

Rcpp_ada_has_port <- function(input) {
    .Call(`_adaR_Rcpp_ada_has_port`, input)
}

Rcpp_ada_has_hash <- function(input) {
    .Call(`_adaR_Rcpp_ada_has_hash`, input)
}

Rcpp_ada_has_search <- function(input) {
    .Call(`_adaR_Rcpp_ada_has_search`, input)
}

Rcpp_ada_get_href <- function(input_vec, length_vec) {
    .Call(`_adaR_Rcpp_ada_get_href`, input_vec, length_vec)
}

Rcpp_ada_get_username <- function(input_vec, length_vec) {
    .Call(`_adaR_Rcpp_ada_get_username`, input_vec, length_vec)
}

Rcpp_ada_get_password <- function(input_vec, length_vec) {
    .Call(`_adaR_Rcpp_ada_get_password`, input_vec, length_vec)
}

Rcpp_ada_get_port <- function(input_vec, length_vec) {
    .Call(`_adaR_Rcpp_ada_get_port`, input_vec, length_vec)
}

Rcpp_ada_get_hash <- function(input_vec, length_vec) {
    .Call(`_adaR_Rcpp_ada_get_hash`, input_vec, length_vec)
}

Rcpp_ada_get_host <- function(input_vec, length_vec) {
    .Call(`_adaR_Rcpp_ada_get_host`, input_vec, length_vec)
}

Rcpp_ada_get_hostname <- function(input_vec, length_vec) {
    .Call(`_adaR_Rcpp_ada_get_hostname`, input_vec, length_vec)
}

Rcpp_ada_get_pathname <- function(input_vec, length_vec) {
    .Call(`_adaR_Rcpp_ada_get_pathname`, input_vec, length_vec)
}

Rcpp_ada_get_search <- function(input_vec, length_vec) {
    .Call(`_adaR_Rcpp_ada_get_search`, input_vec, length_vec)
}

Rcpp_ada_get_protocol <- function(input_vec, length_vec) {
    .Call(`_adaR_Rcpp_ada_get_protocol`, input_vec, length_vec)
}

#' Function to percent-decode characters in URLs
#'
#' Similar to [utils::URLdecode]
#'
#' @param url a character vector
#' @export
#' @examples
#' url_decode("Hello%20World")
url_decode <- function(url) {
    .Call(`_adaR_url_decode`, url)
}

